// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BookItems.Site {
	
	
	public partial class ChangePassword {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.WebControls.TextBox currentPasswordTextBox;
		
		protected System.Web.UI.WebControls.TextBox newPasswordTextBox;
		
		protected System.Web.UI.WebControls.TextBox confirmPasswordTextBox;
		
		protected System.Web.UI.WebControls.Button changePasswordButton;
		
		protected System.Web.UI.WebControls.Label errorLabel;
	}
}
