// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BookItems.Site {
	
	
	public partial class Login {
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.WebControls.Image gcgfgImage;
		
		protected System.Web.UI.WebControls.Label loginErrorLabel;
		
		protected System.Web.UI.WebControls.TextBox userNameTextBox;
		
		protected System.Web.UI.WebControls.TextBox passwordTextBox;
		
		protected System.Web.UI.WebControls.Button loginButton;
	}
}
